"""Generator Output Docstrings

The docstrings for auto-generated files by scripts.

Docstrings:
    ERROR_CODE_SOURCE_DOCSTRING: The file-level docstring for `ErrorCode` Enum
        Python code that contains definitions of different error codes.
"""

ERROR_CODE_SOURCE_DOCSTRING = (
    "ErrorCode Enum\n"
    "\n"
    "This file is auto-generated.\n"
    "***DO NOT EDIT MANUALLY.***\n"
    "\n"
    "Format: LLL-SSS-CCC-VVV\n"
    "   - LLL: Layer (refer to 'Layers' section below)\n"
    "   - SSS: Service code (2-4 uppercased letters)\n"
    "   - CCC: Category (refer to 'Categories' section below)\n"
    "   - VVV: Sequential number (001+)\n"
    "\n"
    "Layers:\n"
    "   APP: `Application`, orchestration layer, services, API\n"
    "   COR: `Core`, foundational concerns\n"
    "   DOM: `Domain`, business logic\n"
    "   INF: `Infrastructure`, external integration layers\n"
    "\n"
    "Categories:\n"
    "   AUTH: `Authentication`, verification or permission failures\n"
    "   CFG: `Configuration`, missing, invalid, or conflicting configs\n"
    "   IO: `Input/Output`, read/write issues\n"
    "   LOOK: 'Look Up`, \n"
    "   SYS: `System`, internal runtime failures\n"
    "   UNK: `Unknown`, unexpected/unclassified, or generic errors\n"
    "   VAL: `Validation`, input/data format validation\n"
    "\n"
    "Generated by: `{PROJECT_ROOT}/scripts/exceptions/error_code_generator.py`\n"
)
