"""ErrorCode Enum

This file is auto-generated.
***DO NOT EDIT MANUALLY.***

Format: LLL-SSS-CCC-VVV
   - LLL: Layer (refer to 'Layers' section below)
   - SSS: Service code (2-4 uppercased letters)
   - CCC: Category (refer to 'Categories' section below)
   - VVV: Sequential number (001+)

Layers:
   APP: `Application`, orchestration layer, services, API
   COR: `Core`, foundational concerns
   DOM: `Domain`, business logic
   INF: `Infrastructure`, external integration layers

Categories:
   AUTH: `Authentication`, verification or permission failures
   CFG: `Configuration`, missing, invalid, or conflicting configs
   IO: `Input/Output`, read/write issues
   LOOK: 'Look Up`, 
   SYS: `System`, internal runtime failures
   UNK: `Unknown`, unexpected/unclassified, or generic errors
   VAL: `Validation`, input/data format validation

Generated by: `{PROJECT_ROOT}/scripts/exceptions/error_code_generator.py`
"""

from enum import StrEnum

class ErrorCode(StrEnum):
    SYS_UNK_UNK_100 = 'SYS-UNK-UNK-100'  # Base for system error - Dont use
    APP_UNK_UNK_200 = 'APP-UNK-UNK-200'  # Base application error - Dont use
    COR_UNK_UNK_300 = 'COR-UNK-UNK-300'  # Base core error - Dont use
    COR_UNK_IO_301 = 'COR-UNK-IO-301'  # FileNotFoundError - file to access is not found
    COR_UNK_IO_302 = 'COR-UNK-IO-302'  # FileNotFoundWarning - file is not found, but recoverable
    COR_UNK_IO_303 = 'COR-UNK-IO-303'  # PathNotFoundError - path to access is not found
    COR_UNK_IO_304 = 'COR-UNK-IO-304'  # PathNotFoundWarning - path is not found, but recoverable
    DOM_UNK_UNK_400 = 'DOM-UNK-UNK-400'  # Base domain error - Dont use
    INF_UNK_UNK_500 = 'INF-UNK-UNK-500'  # Base infrastructure error - Dont use
    INF_UNK_LOOK_501 = 'INF-UNK-LOOK-501'  # Failure to lookup something
    INF_UNK_LOOK_502 = 'INF-UNK-LOOK-502'  # Required values are missing
    INF_UNK_LOOK_503 = 'INF-UNK-LOOK-503'  # Accessing nonexistent registry
    INF_UNK_CFG_504 = 'INF-UNK-CFG-504'  # Configuration-related error
    INF_CFGB_LOOK_521 = 'INF-CFGB-LOOK-521'  # Config model does not have name or path
    INF_CFGB_LOOK_522 = 'INF-CFGB-LOOK-522'  # Config model does not have format or date format
    INF_CFGB_LOOK_523 = 'INF-CFGB-LOOK-523'  # Config model does not have file output path
    INF_CFGB_LOOK_524 = 'INF-CFGB-LOOK-524'  # Config model does not have file or console handler
    INF_CFGB_LOOK_525 = 'INF-CFGB-LOOK-525'  # Looking up a nonexistent config builder type
    INF_LOGR_LOOK_526 = 'INF-LOGR-LOOK-526'  # Tried to create duplication of a service logger
    INF_TDET_CFG_527 = 'INF-TDET-CFG-527'  # Failed to detect a config type